### PR TITLE
Conditional inclusion of tests and collections

### PR DESCRIPTION
**Pull request by DasIch**
I'm currently working on a project which requires a certain Python version for certain features and I wanted to be able to nicely include/run the tests for those features, however the only really satisfying solution I came up was changing attest, so I did.

The changes I made allow you to pass a boolean to `Tests.test`, `Tests.register` and `test`. If the boolean is `True` the test or tests are added otherwise they are not, this comes in very nicely if used as decorators.

The changes are documented, tested and backwards compatible; the latter under the assumption tests would have failed if this wouldn't be the case.

### CODE REVIEW

**Comment by dag** [comment]
Why not,

```
if condition:
    @suite.test
    def test(): pass
```

Or keep these features in their own suites and register conditionally in your "root suite"?

```
tests = Tests()

try:
    import optional_dependency
except ImportError:
    pass
else:
    tests.register('tests.optional_dependency.suite')
```

**Comment by DasIch** [comment]
I usually use suites to group tests by the feature/object or location. Grouping those by conditions, such as supported Python version or available dependencies, violates this principle and comes with a higher overhead than my proposed solution.

**Comment by dag** [comment]
I'm wondering if it's too magic to let decorators take arguments or not.

How about,

```
@suite.test_if(condition)
```

or someting like,

```
@suite.test
@only_if(condition)
```

**Comment by DasIch** [comment]
In the second version you need a "magic" attribute so a clear no on that one. I'm open for the first one.

**Comment by dag** [comment]
OTOH it requires an extra function/method for every case, but I think it might read better and is less magic. I'll sleep on it. :)

**Comment by DasIch** [comment]
I've implemented the `_if` thing in another branch https://github.com/DasIch/attest/tree/conditional-inclusion2

**Comment by dag** [comment]
Thanks. I'm leaning towards `_if`; do you have a preference or any thoughts before I decide?

**Comment by DasIch** [comment]
I don't really have a preference when it comes to the API, however looking at the implementation I have to say that `_if` is definitely cleaner and easier to implement. Therefore I think it might be better to go with that.

**Comment by dag** [comment]
Merged, thanks!

Hm I should probably make an AUTHORS or CONTRIBUTORS file…

**Pull request closed without merging**
