### PR TITLE
No capture flag

### PR DESCRIPTION
**Pull request by paradoxxxzero**
Introduce a no-capture cli flag (-n, --no-capture) to allow printing and pdb-ing everywhere (useful for debugging)

### CODE REVIEW

**Comment by dag** [comment]
In case you missed it, verbose=yes will still capture but print any capture regardless of failure, but I guess it's not enough for pdb?

**Comment by paradoxxxzero** [comment]
Verbose is nice but sadly not sufficient for pdb.

**Comment by dag** [comment]
Could you create a separate branch just for the nocapture?

**Comment by paradoxxxzero** [comment]
Sure

**Pull request closed without merging**
