### PR TITLE
Improve unittest compatibility by allowing to add TestCases to Attest col

### PR DESCRIPTION
**Pull request by dottedmag**
Improve unittest compatibility by allowing to add TestCases to Attest collections

v3:
- handle test\* methods

### CODE REVIEW

**Comment by dottedmag** [comment]
ping?

**Comment by dottedmag** [comment]
ping?

**Comment by dottedmag** [comment]
.debug() does not call tearDown() if test function raises an exception. Anyway, thanks, I will use something similar instead.

**Comment by dottedmag** [comment]
Updated:
- got rid of TestCaseTestResult
- uses slightly modified TestCase.debug() instead of heavily modified TestCase.run().

**Comment by SimonSapin** [comment]
@dottedmag , nobody really is maintaining Attest at the moment, see #131

**Pull request closed without merging**
